
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iudkipjfubgorlzckfau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1ZGtpcGpmdWJnb3JsemNrZmF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjY2MzgsImV4cCI6MjA2MjY0MjYzOH0._77RQS2cn1hjloQacLQqdt5jy3zs_lrBz5OiacWUFbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
